##Spring Configuration
server:
  port: 8081
spring:
  application:
    name: msvc-loan-requests
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: /h2
  profiles:
    include:

adapters:
  r2dbc:
    host: ${POSTGRESQL_HOST}
    port: ${POSTGRESQL_PORT}
    database: ${POSTGRESQL_DATABASE}
    schema: ${POSTGRESQL_SCHEMA}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}